security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login

    access_control:
        # Seul l'admin peut accéder à cette zone
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Les utilisateurs logués peuvent accéder à leur profil
        - { path: ^/profile, roles: ROLE_USER }
